export const actionTypes = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    RESET: 'RESET',
    SET: 'SET',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    INCREMENT_ASYNC: 'INCREMENT_ASYNC'

}